export const MANTINE_NOTIFICATION_ERROR_TITLE = 'Something went wrong!'

export const TOPICS = [
  'Abortion',
  'Gun Control',
  'Immigration',
  'Asylum Seekers',
  'Climate Change',
  'Freedom of Speech',
  'the Death Penalty',
  'Foreign Aid',
  'Education',
  'the Rich Tax',
  'Income Inequality',
  'Racial Equality',
  'Prisoner Voting',
  'Euthanasia and Right-to-Die Laws',
  'the Voting Age',
  'Government Tracking',
  'Censorship',
  'Drug Legalization',
  'Womens Rights',
  'LGBTQIA+ Rights',
  'Human Rights',
  'Communism',
  'Income Inequality',
  'International Trade and Tariffs',
  'Privacy Rights',
  'Vaccination Policies and Mandates',
]
